//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DEMOEKZAMEN
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class StoreDBEntities : DbContext
    {
        private static StoreDBEntities context;
        public StoreDBEntities()

            : base("name=StoreDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
        public static StoreDBEntities GetContext()
        {
            if (context == null)
                context = new StoreDBEntities();

            return context;
        }

        public virtual DbSet<Contractor> Contractor { get; set; }
        public virtual DbSet<LoyaltyCard> LoyaltyCard { get; set; }
        public virtual DbSet<Movement> Movement { get; set; }
        public virtual DbSet<OpeningHour> OpeningHour { get; set; }
        public virtual DbSet<Photo> Photo { get; set; }
        public virtual DbSet<PointOfSale> PointOfSale { get; set; }
        public virtual DbSet<Product> Product { get; set; }
        public virtual DbSet<Roles> Roles { get; set; }
        public virtual DbSet<Sale> Sale { get; set; }
        public virtual DbSet<TrafficPaht> TrafficPaht { get; set; }
        public virtual DbSet<Warehouse> Warehouse { get; set; }
        public virtual DbSet<Users> Users { get; set; }
    }
}
